module.exports = {
    host: process.env.CLEARDB_HOST || 'localhost',
    port: 3306,
    user: process.env.CLEARDB_USER || 'root2',
    password: process.env.CLEARDB_PASSWORD || '1234',
    database: process.env.CLEARDB_DATABASE || 'employees',

    table_user: 'user',
    table_employees: 'employees',
    table_salaries: 'salaries',
    view_current_salaries: 'current_salaries',
    table_dept_emp: 'dept_emp',
    table_current_dept_emp: 'current_dept_emp',
    table_departments: 'departments',
    table_dept_manager: 'dept_manager',
    view_current_dept_manager: 'current_dept_manager',
    table_titles: 'titles',
    view_current_titles: 'current_titles',
    index_on_employees: 'index_on_employees',
    // index_on_current_dept_emp: 'index_on_current_dept_emp',
    index_on_current_dept_manager: 'index_on_current_dept_manager',
    index_on_current_salaries: 'index_on_current_salaries',
    queryLimit: 20,
    connectionLimit: 100,
}